spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/auth/realms/movies/protocol/openid-connect/certs
          issuer-uri: http://localhost:9000/auth/realms/movies
          audiences: movies-audience